### ISSUE TITLE
Create a function that goes through the CSV and finds the sum of all spendings for the day

### ISSUE THREAD

**Issue by NikolaBV** [NikolaBV/Console-Spendings-Calculator#33]

**Comment by Amir-Helali** [comment]
@NikolaBV I would like to work on this. Please assign me to work on this issue. Thanks!

**Comment by NikolaBV** [comment]
I just assigned you, you are open to work on the branch! Good luck and update your progress here.

**Comment by NikolaBV** [comment]
> @NikolaBV I would like to work on this. Please assign me to work on this issue. Thanks!

I have laid out my requierments for contributions in the README. Read them before starting to work the the issue, they are pretty simple, Thanks!

**Comment by NikolaBV** [comment]
Also, if you have any other questions I am here, the code and the documentation is not yet that well written and due to that fact it is a little harder to understand or work on so I am here for any questions and suggestions.

**Comment by Amir-Helali** [comment]
@NikolaBV I made a pull request for the changes that address this issue. Please go over them and let me know if it is satisfactory. Thanks!

**Comment by NikolaBV** [comment]
> @NikolaBV I made a pull request for the changes that address this issue. Please go over them and let me know if it is satisfactory. Thanks!

Thank you very much! I am sure you did great but unfortunately I probably won't be able to get to a computer until monday because I am curently traveling but I will do my best to look at your code. Thank you from the effort!
